spring.application.name=AddressBook

spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true

management.endpoint.health.probes.enabled=true
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=when-authorized